apiVersion: v1
entries:
  prometheus:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/prometheus-community/helm-charts
        - name: Upstream Project
          url: https://github.com/prometheus/prometheus
    apiVersion: v2
    appVersion: v3.7.3
    created: "2025-11-11T12:49:59.1717491+05:30"
    dependencies:
    - condition: alertmanager.enabled
      name: alertmanager
      repository: https://prometheus-community.github.io/helm-charts
      version: 1.28.*
    - condition: kube-state-metrics.enabled
      name: kube-state-metrics
      repository: https://prometheus-community.github.io/helm-charts
      version: 6.4.*
    - condition: prometheus-node-exporter.enabled
      name: prometheus-node-exporter
      repository: https://prometheus-community.github.io/helm-charts
      version: 4.49.*
    - condition: prometheus-pushgateway.enabled
      name: prometheus-pushgateway
      repository: https://prometheus-community.github.io/helm-charts
      version: 3.4.*
    description: Prometheus is a monitoring system and time series database.
    digest: d3d6720aadd443259a73259ff56c69a5a008dfaf34992cba5ffd2896d8aa4515
    home: https://prometheus.io/
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    keywords:
    - monitoring
    - prometheus
    kubeVersion: '>=1.19.0-0'
    maintainers:
    - email: gianrubio@gmail.com
      name: gianrubio
      url: https://github.com/gianrubio
    - email: zanhsieh@gmail.com
      name: zanhsieh
      url: https://github.com/zanhsieh
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
      url: https://github.com/Xtigyro
    - email: naseem@transit.app
      name: naseemkullah
      url: https://github.com/naseemkullah
    - email: rootsandtrees@posteo.de
      name: zeritti
      url: https://github.com/zeritti
    name: prometheus
    sources:
    - https://github.com/prometheus/alertmanager
    - https://github.com/prometheus/prometheus
    - https://github.com/prometheus/pushgateway
    - https://github.com/prometheus/node_exporter
    - https://github.com/kubernetes/kube-state-metrics
    type: application
    urls:
    - prometheus-27.44.0.tgz
    version: 27.44.0
generated: "2025-11-11T12:49:59.166962+05:30"
